Testes artefatos JpaRepository
richardaltmayer/fiap-hexagonal-architecture pull request #44
Opened 2024-01-19 00:57 UTC by richardaltmayer

### Objetivo
Testes de integração dos repositórios (`JpaRepository`) que possuem métodos definidos, com exceção do `OrderJpaRepository`, que é usado em regra de negócio a ser movida para o serviço "produção".

### PR relacionado
PR https://github.com/richardaltmayer/fiap-hexagonal-architecture/pull/43 incorporado à branch. Fazer merge somente após ser feito merge do PR relacionado.

2024-01-19 12:42 UTC, galenodemelo commented on src/test/java/com/fiap/restaurant/external/db/product/ImageJpaRepositoryTest.java
> +            imageJpaRepository.save(imageJpa2);
Aqui também, ter um teste só pra salvar

2024-01-19 14:43 UTC, galenodemelo commented on src/test/java/com/fiap/restaurant/external/db/order/ItemProductRepositoryTests.java
Vamos convencionar usar o sufixo `IT.java` para testes de integração, é algo padrão do Maven e o professor usou na aula

2024-01-20 20:02 UTC, joasgarcia requested changes
Consegue colocar uma alteração no Readme sobre como rodar os testes?

2024-01-22 14:44 UTC, galenodemelo commented on src/test/java/com/fiap/restaurant/external/db/customer/CustomerJpaRepositoryIT.java
> +        @Rollback
Massa essa anotação, ein?

2024-01-22 14:44 UTC, galenodemelo commented on src/test/java/com/fiap/restaurant/external/db/order/ItemJpaRepositoryIT.java
> +            assertThat(optionalItemJpa3).isNotPresent();
Essa verificação não faz sentido em um teste que exige encontrar um ID. Ele deveria ficar em um teste próprio

2024-01-22 14:44 UTC, galenodemelo commented on src/test/java/com/fiap/restaurant/external/db/order/ItemJpaRepositoryIT.java
> +            assertThat(itemJpaRepository.existsById(0L)).isFalse();
Aqui também

2024-01-22 14:44 UTC, galenodemelo commented on src/test/java/com/fiap/restaurant/external/db/order/ItemJpaRepositoryIT.java
> +            ItemJpa itemJpa2 = itemJpaRepository.save(ItemTestUtil.generateJpa("Item 2", "Description 2", 12.5));
Ter algo depois de um assert não fere o AAA? Será que isso é um problema?

2024-01-22 14:44 UTC, galenodemelo commented on src/test/java/com/fiap/restaurant/external/db/order/ItemProductRepositoryIT.java
> +        void mustNotFindAllItemProductByItemId() {
`FindAny` me parece mais adequado, pois o `All` dá a entender que alguns poderiam retornar

2024-01-23 01:26 UTC, richardaltmayer commented on src/test/java/com/fiap/restaurant/external/db/order/ItemJpaRepositoryIT.java
> +            assertThat(itemJpaRepository.existsById(0L)).isFalse();
Aqui não sei, pois a ideia é justamente verificar se existe pelo ID.

2024-01-23 01:42 UTC, richardaltmayer commented on src/test/java/com/fiap/restaurant/external/db/order/ItemJpaRepositoryIT.java
> +            ItemJpa itemJpa2 = itemJpaRepository.save(ItemTestUtil.generateJpa("Item 2", "Description 2", 12.5));
Não sei dizer. Mas por via das dúvidas, tentei estabelecer a ordem AAA.

2024-01-27 00:41 UTC, joasgarcia approved these changes

2024-01-27 13:59 UTC, merged